backend:
  name: git-gateway
  accept_roles:
    - admin

public_folder: "/assets"
media_folder: ".vuepress/public/assets"
display_url: https://coloradocommunityradio.com/

collections:
  - name: "pages"
    label: "Pages"
    delete: false
    description: "Individual site pages not part of a collection"
    files:
      - label: "Home"
        name: "home"
        file: "README.md"
        description: "Site home page with paralax landing image"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "string",
              hint: "Title used for browser tab title",
            }
          - {
              label: "Parallax Image",
              name: "parallaxImage",
              widget: "file",
              hint: "Landing Image with paralax effect",
            }
          - {
              label: "Parallax Header",
              name: "parallaxHeader",
              widget: "string",
              hint: "Main heading centered on paralax area",
            }
          - {
              label: "Parallax Content",
              name: "parallaxContent",
              widget: "text",
              hint: "Text block centered on paralax area",
            }
          - label: "Quotes"
            name: "quotes"
            widget: "list"
            fields:
              - {
                  label: "Quote",
                  name: "quote",
                  widget: "string",
                  default: "This is a quote",
                  pattern: [".{,120}", "Must have under 120 characters"],
                  hint: "The quoted text",
                }
              - {
                  label: "Quote Author",
                  name: "quoteName",
                  widget: "string",
                  default: "John Doe",
                  pattern: [".{,30}", "Must have under 30 characters"],
                  hint: "The quoted person",
                }
              - {
                  label: "Author Title",
                  name: "quoteTitle",
                  widget: "string",
                  default: "Member",
                  pattern: [".{,30}", "Must have under 30 characters"],
                  hint: "The quoted persons title in the organization",
                }
              - {
                  label: "Author Avatar",
                  name: "quoteAvatar",
                  widget: "image",
                  default: "/assets/ccrn-icon.jpg",
                  hint: "An image of the quote author",
                }
              
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Bio"
        name: "bio"
        file: "bio.md"
        description: "A bio page"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "string",
              hint: "Title used for page heading and browser tab title",
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "contact.md"
        description: "A contact page with a contact form"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "string",
              hint: "Title used for page heading and browser tab title",
            }
          - {
              label: "Phone",
              name: "phone",
              widget: "string",
              hint: "A phone number for people to contact you at",
            }
          - {
              label: "Email",
              name: "email",
              widget: "string",
              hint: "A email for people to contact you at",
            }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "sample"
    label: "Samples"
    folder: "sample"
    delete: false
    description: "This collection has example markdown content as well as Netlify CMS configuration documentation"
    slug: "{{slug}}"
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "Title used for page heading and browser tab title",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "stations"
    label: "Stations"
    folder: "stations"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Callsign",
          name: "callsign",
          widget: "string",
          hint: "stations callsign eg. KATS",
        }
      - {
          label: "Frequency",
          name: "frequency",
          widget: "string",
          hint: "frequency of station",
        }
      - {
          label: "Website Url",
          name: "web-url",
          widget: "string",
          hint: "url of the stations website",
        }
      - {
          label: "Stream Url",
          name: "stream-url",
          widget: "string",
          hint: "url of your audio stream",
        }
      - {
          label: "Location",
          name: "location",
          widget: "string",
          hint: "town or area",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          hint: "short description",
        }
      - {
          label: "Schedule HTML",
          name: "schedule",
          widget: "string",
          hint: "html schedule embed",
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "archives"
    label: "Archives"
    folder: "archives"
    create: true
    description: "Show off your media content, with Audio, Video, Photo & Embeded content"
    slug: "{{slug}}"
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "Title of the content group",
        }
      - {
          label: "Created",
          name: "created",
          widget: "date",
          format: "MMMM Do YYYY",
          hint: "Date media was created",
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - label: "Media"
        name: "media"
        widget: "list"
        types:
          - label: "Image"
            name: "image"
            widget: "object"
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the image",
                }
              - {
                  label: "Path",
                  name: "path",
                  widget: "string",
                  required: false,
                  hint: "URL of an image",
                }
              - {
                  label: "File",
                  name: "file",
                  widget: "file",
                  required: false,
                  hint: "Upload or select a previously uploaded image",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                  required: false,
                }
          - label: "Audio"
            name: "audio"
            widget: "object"
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the audio file",
                }
              - {
                  label: "Path",
                  name: "path",
                  widget: "string",
                  required: false,
                  hint: "URL to an audio file",
                }
              - {
                  label: "File",
                  name: "file",
                  widget: "file",
                  required: false,
                  hint: "Upload or select a previously uploaded audio file",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                  required: false,
                }
          - label: "Audio Stream"
            name: "stream"
            widget: "object"
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the audio stream",
                }
              - {
                  label: "Stream URL",
                  name: "url",
                  widget: "string",
                  hint: "The URL of an audio stream",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                  required: false,
                }
          - label: "Video"
            name: "video"
            widget: "object"
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the video",
                }
              - {
                  label: "Path",
                  name: "path",
                  widget: "string",
                  required: false,
                  hint: "URL to a video file",
                }
              - {
                  label: "File",
                  name: "file",
                  widget: "file",
                  required: false,
                  hint: "Upload or select a previously uploaded video file",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                  required: false,
                }
          - label: "Youtube"
            name: "youtube"
            widget: "object"
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the Youtube video",
                }
              - {
                  label: "ID",
                  name: "id",
                  widget: "string",
                  required: false,
                  hint: "ID of the Youtube video",
                }
              - {
                  label: "Is a Playlist",
                  name: "playlist",
                  widget: "boolean",
                  required: false,
                  hint: "Is this a playlist?",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                  required: false,
                }
          - label: "Archive.org"
            name: "archive.org"
            widget: "object"
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the Archive",
                }
              - {
                  label: "ID",
                  name: "id",
                  widget: "string",
                  required: false,
                  hint: "ID of the Archive.org archive",
                }
              - {
                  label: "Is a Playlist",
                  name: "playlist",
                  widget: "boolean",
                  required: false,
                  hint: "Is this a playlist?",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                  required: false,
                }
  - name: "events"
    label: "Events"
    folder: "events"
    create: true
    description: "Promote past and future events"
    slug: "{{slug}}"
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "Title of the blog post",
        }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: false,
          hint: "Heading image for post",
        }
      - {
          label: "Event Url",
          name: "url",
          widget: "string",
          required: false,
          hint: "URL of the Event",
        }
      - {
          label: "Facebook Event",
          name: "facebook",
          widget: "string",
          required: false,
          hint: "URL of the Facebook event",
        }
      - {
          label: "Group",
          name: "group",
          widget: "string",
          required: false,
          hint: "Event group name",
        }
      - {
          label: "Group Url",
          name: "groupUrl",
          widget: "string",
          required: false,
          hint: "URL of the group",
        }
      - {
          label: "Venue",
          name: "venue",
          widget: "string",
          required: false,
          hint: "Event venue name",
        }
      - {
          label: "Venue Url",
          name: "venueUrl",
          widget: "string",
          required: false,
          hint: "URL of the venue",
        }
      - {
          label: "Location",
          name: "location",
          widget: "string",
          hint: "Location of the event",
        }
      - {
          label: "Date and Time",
          name: "datetime",
          widget: "datetime",
          format: "MMMM Do YYYY hh:mm a",
          hint: "Date and time of the event",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "docs"
    label: "Docs"
    folder: "docs"
    create: true
    description: "Add a new document"
    slug: "{{slug}}"
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "Title of the document",
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          hint: "A short description for the index page",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "history"
    label: "Timeline"
    folder: "history"
    create: true
    description: "Add items to the timeline"
    slug: "{{slug}}"
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "Title of the event",
        }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: false,
          hint: "Heading image (optional)",
        }
      - {
          label: "Date",
          name: "Date",
          widget: "date",
          format: "MMM Do YY",
          hint: "Date of event. Leave blank for current date.",
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          hint: "A short description for the event displayed timeline",
        }
      - { label: "Body", name: "body", widget: "markdown" }
